---
# tasks file for build-ta-lib

- name: Installing build toos
  apt:
   name: build-essential
   state: latest

- name: Copying source code to host
  copy:
   src: ta-lib
   dest: /tmp/

- name: Running ./configure && make && make install
  shell: cd /tmp/ta-lib && ./configure && make && make install
